modLoader="javafml"
loaderVersion="[35,)"
license="Not specified"

[[mods]]
modId="opitems"
version="1.0.0"
displayName="OPItems"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Kye Gillatt"

[[dependencies.opitems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




